### ISSUE TITLE
Installation error on MavlinkSerial

### ISSUE THREAD

**Issue by emialonzo** [proto3/MAVkit#3]
[ 50%] Building CXX object CMakeFiles/mavkit.dir/src/mavkit/MavlinkSerial.cpp.o
/Users/dronfies/desarrollo/mavlink/MAVkit/src/mavkit/MavlinkSerial.cpp:96:28: error: use of undeclared identifier 'B460800'
            baudrate_val = B460800;
                           ^
/Users/dronfies/desarrollo/mavlink/MAVkit/src/mavkit/MavlinkSerial.cpp:99:28: error: use of undeclared identifier 'B921600'
            baudrate_val = B921600;

I delete those two lines and compile

**Comment by proto3** [comment]
I got no problem here, it seems your system doesn't know these constants. I don't know which OS you are using but it seems both values are defined in Linux termbits.h since 2.6.12-rc2 (2005).

**Comment by proto3** [comment]
I close this issue as it seems to be related to an external missing dependency.
